honor/python/Django/list_view/front/urls.py
from django.urls import path
from . import views

app_name = 'front'

urlpatterns = [
    path('add/', views.add_article, name='add_article'),
    path('list/', views.ArticleListView.as_view(), name='article_list'),
]

honor/python/Django/list_view/list_view/urls.py
from django.contrib import admin
from django.urls import path, include
from front import views

urlpatterns = [
    # path('', views.index, name='index'),
    path('article/', include('front.urls'), name='article'),
]

honor/python/Django/list_view/front/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)

honor/python/Django/list_view/front/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Article
from django.views.generic import ListView


def add_article(request):
    articles = []
    for x in range(1, 107):
        article = Article(title='标题：%s'%x, content='内容：%s'%x)
        articles.append(article)
    Article.objects.bulk_create(articles)
    return HttpResponse("文章添加成功")


class ArticleListView(ListView):
    model = Article
    # template_name = "article_list.html"
    template_name = "article_list1.html"
    context_object_name = "articles"
    paginate_by = 10
    ordering = "create_time"
    # page_kwarg = 'p'

    def get_context_data(self, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        paginator = context.get('paginator')
        page_obj = context.get('page_obj')
        pagination_date = self.get_pagination_date(paginator, page_obj)
        context.update(pagination_date)
        return context

    def get_pagination_date(self, paginator, page_obj, around_count=2):
        current_page = page_obj.number
        num_pages = paginator.num_pages

        left_has_more = False
        right_has_more = False

        if current_page <= around_count+2:
            left_pages = range(1, current_page)
        else:
            left_has_more = True
            left_pages = range(current_page-around_count, current_page)
        if current_page >= num_pages-around_count-1:
            right_pages = range(current_page+1, num_pages+1)
        else:
            right_has_more = True
            right_pages = range(current_page+1, current_page+around_count+1)

        return {
            'left_pages': left_pages,
            'right_pages': right_pages,
            'current_page': current_page,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'num_pages': num_pages,
        }


    # def get_queryset(self):
    #     return Article.objects.all()
    #     return Article.objects.filter(id__gte=27)

honor/python/Django/list_view/templates/article_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表/分页视图</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <ul>
{#    上一页#}
        {% for article in articles %}
            <li>{{ article.title }}</li>
        {% endfor %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="{% url 'front:article_list' %}?page={{ page_obj.previous_page_number }}">上一页</a></li>
            {% else %}
                <li class="disabled"><a href="javascript: void(0);">上一页</a></li>
            {% endif %}

{#        中间页#}
            {% for page in paginator.page_range %}
                {% if page == page_obj.number %}
                    <li class="active"><a href="javascript: void(0);">{{ page }}</a></li>
                {% else %}
                    <li><a href="{% url 'front:article_list' %}?page={{ page }}">{{ page }}</a></li>
                {% endif %}
            {% endfor %}

{#        下一页#}
            {% if page_obj.has_next %}
                <li><a href="{% url 'front:article_list' %}?page={{ page_obj.next_page_number }}">下一页</a></li>
            {% else %}
                <li class="disabled"><a href="javascript: void(0);">下一页</a></li>
            {% endif %}

        </ul>
    </ul>
</body>
</html>

honor/python/Django/list_view/templates/article_list1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表/分页视图</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
<body>
    <ul>
{#    上一页#}
        {% for article in articles %}
            <li>{{ article.title }}</li>
        {% endfor %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="{% url 'front:article_list' %}?page={{ page_obj.previous_page_number }}">上一页</a></li>
            {% else %}
                <li class="disabled"><a href="javascript: void(0);">上一页</a></li>
            {% endif %}
{#中间页#}
            {% if left_has_more %}
                <li><a href="{% url 'front:article_list' %}?page=1">1</a></li>
                <li><a href="javascript: void(0)">...</a></li>
            {% endif %}
{#            当前页码左边的页码#}
            {% for left_page in left_pages %}
                <li><a href="{% url 'front:article_list' %}?page={{ left_page }}">{{ left_page }}</a></li>
            {% endfor %}
{#        当前页码#}
            <li class="active"><a href="{% url 'front:article_list' %}?page={{ current_page }}">{{ current_page }}</a></li>
{#        当前页码右边的页码#}
            {% for right_page in right_pages %}
                <li><a href="{% url 'front:article_list' %}?page={{ right_page }}">{{ right_page }}</a></li>
            {% endfor %}

            {% if right_has_more %}
                <li><a href="javascript: void(0)">...</a></li>
                <li><a href="{% url 'front:article_list' %}?page={{ num_pages }}">{{ num_pages }}</a></li>
            {% endif %}
{#        下一页#}
            {% if page_obj.has_next %}
                <li><a href="{% url 'front:article_list' %}?page={{ page_obj.next_page_number }}">下一页</a></li>
            {% else %}
                <li class="disabled"><a href="javascript: void(0);">下一页</a></li>
            {% endif %}

        </ul>
    </ul>
</body>
</html>