honor/python/xfz/apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('', views.index, name='index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('login/', views.login_view, name='login_view'),
]

honor/python/xfz/apps/xfzauth/urls.py
from django.urls import path
from . import views

app_name = "xfzauth"

urlpatterns = [
    path('login/', views.login_view, name='login')
]

honor/python/xfz/xfz/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.index, name="index"),
    path('cms/', include("apps.cms.urls")),
    path('news/', include("apps.news.urls")),
    path('account/', include("apps.xfzauth.urls")),
    path('course/', include('apps.course.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

honor/python/xfz/apps/cms/models.py
from django.db import models

# Create your models here.

honor/python/xfz/apps/cms/forms.py
from apps.forms import FormMixin
from django import forms


class EditNewsCategory(forms.Form):
    pk = forms.IntegerField()
    name = forms.CharField(max_length=100)

honor/python/xfz/apps/cms/views.py
from django.shortcuts import render
from django.views.generic import View
from django.views.decorators.http import require_POST, require_GET
from apps.news.models import NewsCategory
from utils import restful
from .forms import EditNewsCategory
from django.views.decorators.csrf import csrf_exempt
import os
from django.conf import settings


def login_view(request):
    return render(request, 'cms/login.html')


def index(request):
    return render(request, 'cms/index.html')


class WriteNewsView(View):
    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {
            'categories': categories
        }
        return render(request, 'cms/write_news.html', context=context)


@require_GET
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {
        'categories': categories
    }
    return render(request, 'cms/news_category.html', context=context)


@require_POST
def add_news_category(request):
    name = request.POST.get("name")
    exists = NewsCategory.objects.filter(name=name).exists()
    if not exists:
        NewsCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message='this is a bug')


@require_POST
def edit_news_category(request):
    form = EditNewsCategory(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message="该分类不存在")
    else:
        return restful.params_error(message='该分类不存在')
    

@require_POST
def delete_news_category(request):
    pk = request.POST.get('pk')
    try:
        NewsCategory.objects.filter(pk=pk).delete()
        return restful.ok()
    except:
        return restful.unauth(message='该分类不存在！')


@csrf_exempt
@require_POST
def upload_file(request):
    file = request.FILES.get('file')
    name = file.name
    with open(os.path.join(settings.MEDIA_ROOT, name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    return restful.result(data={'url': url})

honor/python/xfz/front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | 小饭桌后台管理系统</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/jqvmap/jqvmap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{% static 'adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1433630_66m67rbe3bp.css">
    <link rel="favicon icon" href="{% static 'images/favicon.ico' %}" type="images/x-icon">
    <!-- jQuery -->
    <script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="{% static 'adminlte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- ChartJS -->

    <!-- AdminLTE App -->
    <script src="{% static 'adminlte/dist/js/adminlte.js' %}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{% static 'adminlte/dist/js/pages/dashboard.js' %}"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="{% static 'adminlte/dist/js/demo.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{% static 'adminlte/index3.html' %}" class="nav-link">首页</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">Contact</a>
            </li>
        </ul>

        <!-- SEARCH FORM -->
        <form class="form-inline ml-3">
            <div class="input-group input-group-sm">
                <input class="form-control form-control-navbar" type="search" placeholder="搜索" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-navbar" type="submit">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="#" class="brand-link">
            <img src="{% static 'adminlte/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo"
                 class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light"><b>小饭桌管理系统</b></span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="{% static 'adminlte/dist/img/user2-160x160.jpg' %}" class="img-circle elevation-2"
                         alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">邵彦亮</a>
                </div>
            </div>
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <span class="iconfont icon-shouye" style="font-size: 24px;color: #ccc;margin-left: 20px"></span>
                <div class="info">
                    <a href="{% url 'cms:index' %}" class="d-block"><b>首页</b></a>
                </div>
            </div>
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="info">
                    <a href="#" class="d-block">新闻管理</a>
                    <a href="{% url 'cms:write_news' %}" class="d-block">
                        <i class="fa fa-edit"></i>
                        <span>发布新闻</span>
                    </a>
                    <a href="{% url 'cms:news_category' %}" class="d-block">
                        <i class="fa fa-tag"></i>
                        <span>新闻分类</span>
                    </a>
                </div>
            </div>
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <section class="content-header">
            {% block content-header %}{% endblock %}
        </section>
        <section class="content">
            {% block content %}{% endblock %}
        </section>
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>Copyright &copy; 2014-2019 <a href="#">小饭桌后台管理系统</a>.</strong>
        版权所有
        <div class="float-right d-none d-sm-inline-block">
            <b>版本</b> 3.0.1
        </div>
    </footer>
</div>
<!-- ./wrapper -->
</body>
</html>

honor/python/xfz/front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}首页{% endblock %}

{% block content-header %}
    <h1>欢迎来到小饭桌CMS管理系统</h1>
{% endblock %}

honor/python/xfz/front/templates/cms/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>小饭桌管理系统</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="#"><b>小饭桌管理系统</b></a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">请登录</p>

      <form action="{% url 'xfzauth:login' %}" method="post">
          {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" name="telephone" placeholder="手机号码">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control" placeholder="密码">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember" name="remember" value="1">
              <label for="remember" style="font-size: 14px;font-weight: normal">
                记住密码
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">登录</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <!-- /.social-auth-links -->

{#      <p class="mb-1">#}
{#        <a href="{% static 'adminlte/pages/examples/forgot-password.html' %}">忘记密码</a>#}
{#      </p>#}
{#      <p class="mb-0">#}
{#        <a href="{% static 'adminlte/pages/examples/register.html' %}" class="text-center">注册新账号</a>#}
{#      </p>#}
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlte/dist/js/adminlte.min.js' %}"></script>

</body>
</html>

honor/python/xfz/front/templates/cms/news_category.html
{% extends 'cms/base.html' %}

{% block title %}
    新闻分类
{% endblock %}

{% block head %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script>
        $.ajaxSetup({
            data:{csrfmiddlewaretoken:'{{ csrf_token }}'}
        })
    </script>
    <script src="{% static 'js/news_category.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1>新闻分类</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <button id="add-btn" class="btn btn-primary float-right">添加分类</button>
                </div>
                <div class="box-body">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>分类名称</th>
                                <th>新闻数量</th>
                                <th>操作</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for category in categories %}
                            <tr data-pk="{{ category.pk }}" data-name="{{ category.name }}">
                                <td>{{ category.name }}</td>
                                <td>20</td>
                                <td>
                                    <button class="btn btn-warning btn-xs edit-btn">编辑</button>
                                    <button class="btn btn-danger btn-xs delete-btn">删除</button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

honor/python/xfz/front/templates/cms/write_news.html
{% extends 'cms/base.html' %}

{% block title %}发布新闻{% endblock %}

{% block content-header %}
    <h1>发布新闻</h1>
{% endblock %}

{% block head %}
    <script src="{% static 'ueditor/ueditor.config.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.all.min.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.parse.min.js' %}"></script>
    <script src="{% static 'js/write_news.min.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">编辑文本</h3>
                </div>
                <form action="#" class="form">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="title-form">标题</label>
                            <input type="text" id="title-form" class="form-control" name="title" placeholder="请输入文章标题">
                        </div>
                        <div class="form-group">
                            <label for="category-form">分类</label>
                            <select name="category" id="category-form" class="form-control">
                                {% for category in categories %}
                                    <option value="{{ category.pk }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="desc-form">描述</label>
                            <input type="text" class="form-control" id="desc-form" name="desc">
                        </div>
                        <div class="form-group">
                            <label for="thumbnail-form" class="thumbnail-form">缩略图</label>
                            <div class="input-group">
                                <input type="text" id="thumbnail-form" class="form-control" name="thumbnail">
                                <span class="input-group-btn">
                                    <label class="btn btn-default btn-file">
                                        上传图片<input hidden class="btn btn-default" type="file" id="thumbnail-btn">
                                    </label>
                                </span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="content-form">内容</label>
                            <script id="editor" type="text/plain"></script>
                        </div>
                    </div>
                    <div class="card-footer">
                        <button class="btn btn-primary float-right">发布新闻</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}